//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 03:53:43 PM CEST 
//


package com.polopoly.xml.app;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}viewer" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}field"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}help"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}idparam"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}idparam-list"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}layout"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}param"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}policy"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="externalid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="input-template" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "viewer",
    "fieldOrHelpOrIdparam"
})
@XmlRootElement(name = "field")
public class Field {

    protected Viewer viewer;
    @XmlElementRefs({
        @XmlElementRef(name = "policy", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = JAXBElement.class),
        @XmlElementRef(name = "param", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Param.class),
        @XmlElementRef(name = "help", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = JAXBElement.class),
        @XmlElementRef(name = "field", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Field.class),
        @XmlElementRef(name = "idparam", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Idparam.class),
        @XmlElementRef(name = "idparam-list", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = IdparamList.class),
        @XmlElementRef(name = "layout", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Layout.class)
    })
    protected List<Object> fieldOrHelpOrIdparam;
    @XmlAttribute(name = "default")
    @XmlSchemaType(name = "anySimpleType")
    protected String _default;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String externalid;
    @XmlAttribute(name = "input-template", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String inputTemplate;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String label;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute
    protected Boolean required;

    /**
     * Gets the value of the viewer property.
     * 
     * @return
     *     possible object is
     *     {@link Viewer }
     *     
     */
    public Viewer getViewer() {
        return viewer;
    }

    /**
     * Sets the value of the viewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Viewer }
     *     
     */
    public void setViewer(Viewer value) {
        this.viewer = value;
    }

    /**
     * Gets the value of the fieldOrHelpOrIdparam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrHelpOrIdparam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrHelpOrIdparam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Param }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Field }
     * {@link Idparam }
     * {@link IdparamList }
     * {@link Layout }
     * 
     * 
     */
    public List<Object> getFieldOrHelpOrIdparam() {
        if (fieldOrHelpOrIdparam == null) {
            fieldOrHelpOrIdparam = new ArrayList<Object>();
        }
        return this.fieldOrHelpOrIdparam;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the externalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalid() {
        return externalid;
    }

    /**
     * Sets the value of the externalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalid(String value) {
        this.externalid = value;
    }

    /**
     * Gets the value of the inputTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputTemplate() {
        return inputTemplate;
    }

    /**
     * Sets the value of the inputTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputTemplate(String value) {
        this.inputTemplate = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

}
