//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 03:53:43 PM CEST 
//


package com.polopoly.xml.app;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}content-list-wrapper"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}layoutClass"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}content-xml"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}field"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}help"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}idparam"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}idparam-list"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}layout"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}param"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}policy"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}viewer"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}content-list"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}editor"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}output-templates"/>
 *           &lt;element ref="{http://www.polopoly.com/polopoly/cm/app/xml}type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="system-template" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contentListWrapper",
    "layoutClass",
    "contentXmlOrFieldOrHelp"
})
@XmlRootElement(name = "input-template")
public class InputTemplate {

    @XmlElement(name = "content-list-wrapper")
    protected String contentListWrapper;
    protected String layoutClass;
    @XmlElementRefs({
        @XmlElementRef(name = "policy", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = JAXBElement.class),
        @XmlElementRef(name = "param", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Param.class),
        @XmlElementRef(name = "type", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = JAXBElement.class),
        @XmlElementRef(name = "help", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = JAXBElement.class),
        @XmlElementRef(name = "idparam", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Idparam.class),
        @XmlElementRef(name = "idparam-list", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = IdparamList.class),
        @XmlElementRef(name = "viewer", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Viewer.class),
        @XmlElementRef(name = "editor", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Editor.class),
        @XmlElementRef(name = "field", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Field.class),
        @XmlElementRef(name = "content-list", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = ContentList.class),
        @XmlElementRef(name = "output-templates", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = OutputTemplates.class),
        @XmlElementRef(name = "content-xml", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = ContentXml.class),
        @XmlElementRef(name = "layout", namespace = "http://www.polopoly.com/polopoly/cm/app/xml", type = Layout.class)
    })
    protected List<Object> contentXmlOrFieldOrHelp;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String label;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "system-template")
    protected Boolean systemTemplate;

    /**
     * Gets the value of the contentListWrapper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentListWrapper() {
        return contentListWrapper;
    }

    /**
     * Sets the value of the contentListWrapper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentListWrapper(String value) {
        this.contentListWrapper = value;
    }

    /**
     * Gets the value of the layoutClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutClass() {
        return layoutClass;
    }

    /**
     * Sets the value of the layoutClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutClass(String value) {
        this.layoutClass = value;
    }

    /**
     * Gets the value of the contentXmlOrFieldOrHelp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentXmlOrFieldOrHelp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentXmlOrFieldOrHelp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Param }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Idparam }
     * {@link IdparamList }
     * {@link Viewer }
     * {@link Editor }
     * {@link Field }
     * {@link ContentList }
     * {@link OutputTemplates }
     * {@link ContentXml }
     * {@link Layout }
     * 
     * 
     */
    public List<Object> getContentXmlOrFieldOrHelp() {
        if (contentXmlOrFieldOrHelp == null) {
            contentXmlOrFieldOrHelp = new ArrayList<Object>();
        }
        return this.contentXmlOrFieldOrHelp;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the systemTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSystemTemplate() {
        return systemTemplate;
    }

    /**
     * Sets the value of the systemTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSystemTemplate(Boolean value) {
        this.systemTemplate = value;
    }

}
