//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 03:53:43 PM CEST 
//


package com.polopoly.xml.app;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.polopoly.xml.app package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Type_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "type");
    private final static QName _Major_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "major");
    private final static QName _Policy_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "policy");
    private final static QName _LayoutClass_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "layoutClass");
    private final static QName _Minor_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "minor");
    private final static QName _ContentListWrapper_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "content-list-wrapper");
    private final static QName _Id_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "id");
    private final static QName _Help_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "help");
    private final static QName _Externalid_QNAME = new QName("http://www.polopoly.com/polopoly/cm/app/xml", "externalid");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.polopoly.xml.app
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Contentid }
     * 
     */
    public Contentid createContentid() {
        return new Contentid();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link OutputTemplate }
     * 
     */
    public OutputTemplate createOutputTemplate() {
        return new OutputTemplate();
    }

    /**
     * Create an instance of {@link Idparam }
     * 
     */
    public Idparam createIdparam() {
        return new Idparam();
    }

    /**
     * Create an instance of {@link IdparamList }
     * 
     */
    public IdparamList createIdparamList() {
        return new IdparamList();
    }

    /**
     * Create an instance of {@link Viewer }
     * 
     */
    public Viewer createViewer() {
        return new Viewer();
    }

    /**
     * Create an instance of {@link Editor }
     * 
     */
    public Editor createEditor() {
        return new Editor();
    }

    /**
     * Create an instance of {@link InputTemplate }
     * 
     */
    public InputTemplate createInputTemplate() {
        return new InputTemplate();
    }

    /**
     * Create an instance of {@link TemplateDefinition }
     * 
     */
    public TemplateDefinition createTemplateDefinition() {
        return new TemplateDefinition();
    }

    /**
     * Create an instance of {@link Contentref }
     * 
     */
    public Contentref createContentref() {
        return new Contentref();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link ContentList }
     * 
     */
    public ContentList createContentList() {
        return new ContentList();
    }

    /**
     * Create an instance of {@link OutputTemplates }
     * 
     */
    public OutputTemplates createOutputTemplates() {
        return new OutputTemplates();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link ContentXml }
     * 
     */
    public ContentXml createContentXml() {
        return new ContentXml();
    }

    /**
     * Create an instance of {@link Layout }
     * 
     */
    public Layout createLayout() {
        return new Layout();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "major")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMajor(String value) {
        return new JAXBElement<String>(_Major_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "policy")
    public JAXBElement<String> createPolicy(String value) {
        return new JAXBElement<String>(_Policy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "layoutClass")
    public JAXBElement<String> createLayoutClass(String value) {
        return new JAXBElement<String>(_LayoutClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "minor")
    public JAXBElement<BigInteger> createMinor(BigInteger value) {
        return new JAXBElement<BigInteger>(_Minor_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "content-list-wrapper")
    public JAXBElement<String> createContentListWrapper(String value) {
        return new JAXBElement<String>(_ContentListWrapper_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "help")
    public JAXBElement<String> createHelp(String value) {
        return new JAXBElement<String>(_Help_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.polopoly.com/polopoly/cm/app/xml", name = "externalid")
    public JAXBElement<String> createExternalid(String value) {
        return new JAXBElement<String>(_Externalid_QNAME, String.class, null, value);
    }

}
